version: '2'
services:
  bind:
    image:"sameersbn/bind:9.11.3-20190113"
    volumes:
      - /data/data/bind:/data
    ports:
      - "10000:10000/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - "ROOT_PASSWORD=mydns"